#pragma once

#include <cstddef>
#include <cstring>

namespace dalian {

struct FactionDef {
  const char* country;
  const char* army;
  const char* region;
};

namespace detail {

inline constexpr FactionDef kFactions[] = {
    {"United States", "United States Army / USMC", "North America"},
    {"United Kingdom", "British Army", "Europe"},
    {"Russia", "Russian Ground Forces", "Europe"},
    {"China", "People's Liberation Army Ground Force", "Asia"},
    {"Ukraine", "Ukrainian Ground Forces", "Europe"},
    {"Iran", "Islamic Republic of Iran Army", "Asia"},
    {"North Korea", "Korean People's Army Ground Force", "Asia"},
    {"Afghanistan", "Islamic Emirate Army", "Asia"},
    {"France", "French Army", "Europe"},
    {"Germany", "German Army (Heer)", "Europe"},
    {"Poland", "Polish Land Forces", "Europe"},
    {"Algeria", "Algerian People's National Army", "Africa"},
    {"Angola", "Angolan Land Forces", "Africa"},
    {"Benin", "Benin Army", "Africa"},
    {"Botswana", "Botswana Ground Force", "Africa"},
    {"Burkina Faso", "Burkina Faso Army", "Africa"},
    {"Burundi", "Burundi National Defence Force", "Africa"},
    {"Cameroon", "Cameroonian Army", "Africa"},
    {"Cape Verde", "Cape Verdean National Guard", "Africa"},
    {"Central African Republic", "Central African Republic Ground Forces", "Africa"},
    {"Chad", "Chadian Ground Forces", "Africa"},
    {"Comoros", "Comorian Security Force", "Africa"},
    {"DR Congo", "Land Forces of the DRC", "Africa"},
    {"Republic of Congo", "Congolese Army", "Africa"},
    {"Djibouti", "Djiboutian Army", "Africa"},
    {"Egypt", "Egyptian Army", "Africa"},
    {"Equatorial Guinea", "Equatorial Guinean Army", "Africa"},
    {"Eritrea", "Eritrean Army", "Africa"},
    {"Eswatini", "Umbutfo Eswatini Defence Force", "Africa"},
    {"Ethiopia", "Ethiopian Ground Forces", "Africa"},
    {"Gabon", "Gabonese Army", "Africa"},
    {"Gambia", "Gambian National Army", "Africa"},
    {"Ghana", "Ghana Army", "Africa"},
    {"Guinea", "Guinean Army", "Africa"},
    {"Guinea-Bissau", "Guinea-Bissau Army", "Africa"},
    {"Ivory Coast", "Ivorian Army", "Africa"},
    {"Kenya", "Kenya Army", "Africa"},
    {"Lesotho", "Lesotho Defence Force", "Africa"},
    {"Liberia", "Armed Forces of Liberia", "Africa"},
    {"Libya", "Libyan Ground Forces", "Africa"},
    {"Madagascar", "Malagasy Army", "Africa"},
    {"Malawi", "Malawian Army", "Africa"},
    {"Mali", "Malian Army", "Africa"},
    {"Mauritania", "Mauritanian Army", "Africa"},
    {"Morocco", "Royal Moroccan Army", "Africa"},
    {"Mozambique", "Mozambican Army", "Africa"},
    {"Namibia", "Namibian Army", "Africa"},
    {"Niger", "Niger Army", "Africa"},
    {"Nigeria", "Nigerian Army", "Africa"},
    {"Rwanda", "Rwandan Land Forces", "Africa"},
    {"Sao Tome and Principe", "Armed Forces of Sao Tome and Principe", "Africa"},
    {"Senegal", "Senegalese Army", "Africa"},
    {"Seychelles", "Seychelles Infantry Unit", "Africa"},
    {"Sierra Leone", "Republic of Sierra Leone Armed Forces", "Africa"},
    {"Somalia", "Somali National Army", "Africa"},
    {"South Africa", "South African Army", "Africa"},
    {"South Sudan", "South Sudan People's Defence Forces", "Africa"},
    {"Sudan", "Sudanese Army", "Africa"},
    {"Tanzania", "Tanzania Army", "Africa"},
    {"Togo", "Togolese Army", "Africa"},
    {"Tunisia", "Tunisian Land Forces", "Africa"},
    {"Uganda", "Ugandan Land Forces", "Africa"},
    {"Zambia", "Zambian Army", "Africa"},
    {"Zimbabwe", "Zimbabwe National Army", "Africa"},
    {"Armenia", "Armenian Army", "Asia"},
    {"Azerbaijan", "Azerbaijani Land Forces", "Asia"},
    {"Bahrain", "Royal Bahraini Army", "Asia"},
    {"Bangladesh", "Bangladesh Army", "Asia"},
    {"Bhutan", "Royal Bhutan Army", "Asia"},
    {"Brunei", "Royal Brunei Land Force", "Asia"},
    {"Cambodia", "Royal Cambodian Army", "Asia"},
    {"East Timor", "F-FDTL Land Component", "Asia"},
    {"India", "Indian Army", "Asia"},
    {"Indonesia", "Indonesian Army", "Asia"},
    {"Iraq", "Iraqi Army", "Asia"},
    {"Israel", "Israel Defense Forces", "Asia"},
    {"Japan", "Japan Ground Self-Defense Force", "Asia"},
    {"Jordan", "Royal Jordanian Land Force", "Asia"},
    {"Kazakhstan", "Kazakh Ground Forces", "Asia"},
    {"Kuwait", "Kuwaiti Land Force", "Asia"},
    {"Kyrgyzstan", "Kyrgyz Ground Forces", "Asia"},
    {"Laos", "Lao People's Army", "Asia"},
    {"Lebanon", "Lebanese Army", "Asia"},
    {"Malaysia", "Malaysian Army", "Asia"},
    {"Maldives", "Maldives National Defence Force", "Asia"},
    {"Mongolia", "Mongolian Ground Forces", "Asia"},
    {"Myanmar", "Myanmar Army", "Asia"},
    {"Nepal", "Nepalese Army", "Asia"},
    {"Oman", "Royal Army of Oman", "Asia"},
    {"Pakistan", "Pakistan Army", "Asia"},
    {"Philippines", "Philippine Army", "Asia"},
    {"Qatar", "Qatari Land Force", "Asia"},
    {"Saudi Arabia", "Royal Saudi Land Forces", "Asia"},
    {"Singapore", "Singapore Army", "Asia"},
    {"South Korea", "Republic of Korea Army", "Asia"},
    {"Sri Lanka", "Sri Lanka Army", "Asia"},
    {"Syria", "Syrian Arab Army", "Asia"},
    {"Taiwan", "Republic of China Army", "Asia"},
    {"Tajikistan", "Tajik Ground Forces", "Asia"},
    {"Thailand", "Royal Thai Army", "Asia"},
    {"Turkey", "Turkish Land Forces", "Asia"},
    {"Turkmenistan", "Turkmen Ground Forces", "Asia"},
    {"UAE", "United Arab Emirates Army", "Asia"},
    {"Uzbekistan", "Uzbek Ground Forces", "Asia"},
    {"Vietnam", "People's Army of Vietnam", "Asia"},
    {"Yemen", "Yemeni Army", "Asia"},
    {"Albania", "Albanian Land Force", "Europe"},
    {"Austria", "Austrian Land Forces", "Europe"},
    {"Belarus", "Belarusian Ground Forces", "Europe"},
    {"Belgium", "Belgian Land Component", "Europe"},
    {"Bosnia", "Bosnian Ground Forces", "Europe"},
    {"Bulgaria", "Bulgarian Land Forces", "Europe"},
    {"Croatia", "Croatian Army", "Europe"},
    {"Cyprus", "Cypriot National Guard", "Europe"},
    {"Czech Republic", "Czech Land Forces", "Europe"},
    {"Denmark", "Royal Danish Army", "Europe"},
    {"Estonia", "Estonian Land Forces", "Europe"},
    {"Finland", "Finnish Army", "Europe"},
    {"Georgia", "Georgian Land Forces", "Europe"},
    {"Greece", "Hellenic Army", "Europe"},
    {"Hungary", "Hungarian Ground Forces", "Europe"},
    {"Ireland", "Irish Army", "Europe"},
    {"Italy", "Italian Army", "Europe"},
    {"Latvia", "Latvian Land Forces", "Europe"},
    {"Lithuania", "Lithuanian Land Forces", "Europe"},
    {"Luxembourg", "Luxembourg Army", "Europe"},
    {"Malta", "Armed Forces of Malta", "Europe"},
    {"Moldova", "Moldovan Ground Forces", "Europe"},
    {"Monaco", "Compagnie des Carabiniers du Prince", "Europe"},
    {"Montenegro", "Montenegrin Ground Army", "Europe"},
    {"Netherlands", "Royal Netherlands Army", "Europe"},
    {"North Macedonia", "Army of North Macedonia", "Europe"},
    {"Norway", "Norwegian Army", "Europe"},
    {"Portugal", "Portuguese Army", "Europe"},
    {"Romania", "Romanian Land Forces", "Europe"},
    {"San Marino", "Sammarinese Armed Forces", "Europe"},
    {"Serbia", "Serbian Army", "Europe"},
    {"Slovakia", "Slovak Land Forces", "Europe"},
    {"Slovenia", "Slovenian Ground Forces", "Europe"},
    {"Spain", "Spanish Army", "Europe"},
    {"Sweden", "Swedish Army", "Europe"},
    {"Switzerland", "Swiss Land Forces", "Europe"},
    {"Vatican City", "Swiss Guard", "Europe"},
    {"Antigua and Barbuda", "Antigua and Barbuda Regiment", "Americas"},
    {"Bahamas", "Royal Bahamas Defence Force", "Americas"},
    {"Barbados", "Barbados Regiment", "Americas"},
    {"Belize", "Belize Defence Force", "Americas"},
    {"Canada", "Canadian Army", "Americas"},
    {"Cuba", "Cuban Revolutionary Army", "Americas"},
    {"Dominican Republic", "Dominican Republic Army", "Americas"},
    {"El Salvador", "Salvadoran Army", "Americas"},
    {"Guatemala", "Guatemalan Army", "Americas"},
    {"Honduras", "Honduran Army", "Americas"},
    {"Jamaica", "Jamaica Defence Force", "Americas"},
    {"Mexico", "Mexican Army", "Americas"},
    {"Nicaragua", "National Army of Nicaragua", "Americas"},
    {"Saint Kitts and Nevis", "Saint Kitts and Nevis Defence Force", "Americas"},
    {"Trinidad and Tobago", "Trinidad and Tobago Regiment", "Americas"},
    {"Argentina", "Argentine Army", "South America"},
    {"Bolivia", "Bolivian Army", "South America"},
    {"Brazil", "Brazilian Army", "South America"},
    {"Chile", "Chilean Army", "South America"},
    {"Colombia", "National Army of Colombia", "South America"},
    {"Ecuador", "Ecuadorian Army", "South America"},
    {"Guyana", "Guyana Defence Force", "South America"},
    {"Paraguay", "Paraguayan Army", "South America"},
    {"Peru", "Peruvian Army", "South America"},
    {"Suriname", "Surinamese Army", "South America"},
    {"Uruguay", "National Army of Uruguay", "South America"},
    {"Venezuela", "Venezuelan National Army", "South America"},
    {"Australia", "Australian Army", "Oceania"},
    {"Fiji", "Republic of Fiji Military Forces", "Oceania"},
    {"New Zealand", "New Zealand Army", "Oceania"},
    {"Papua New Guinea", "Papua New Guinea Defence Force", "Oceania"},
    {"Tonga", "Tongan Land Forces", "Oceania"},
};

}  // namespace detail

inline const FactionDef* all_factions() { return detail::kFactions; }

inline std::size_t faction_count() { return std::size(detail::kFactions); }

inline const FactionDef& faction_at(int id) {
  const std::size_t n = faction_count();
  if (id < 0 || static_cast<std::size_t>(id) >= n) return detail::kFactions[0];
  return detail::kFactions[static_cast<std::size_t>(id)];
}

inline int faction_kit_side(int faction_id) {
  const auto& f = faction_at(faction_id);
  if (std::strcmp(f.country, "Russia") == 0 || std::strcmp(f.country, "China") == 0 ||
      std::strcmp(f.country, "Iran") == 0 || std::strcmp(f.country, "North Korea") == 0 ||
      std::strcmp(f.country, "Afghanistan") == 0)
    return 1;
  return faction_id % 2;
}

}  // namespace dalian
